AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
  TargetRubyVersion: 2.4

Naming/FileName:
  Description: Use snake_case for source file names.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#snake-case-files
  Enabled: true
  Exclude:
    - lib/benchmark-memory.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - spec/**/*.rb

# TODO: don't know how to fix, false positive?
# https://github.com/rubocop-hq/rubocop/issues/5953
Style/AccessModifierDeclarations:
  Exclude:
    - lib/benchmark/memory/helpers.rb
